### PR TITLE
Atomixrex-xml-instead-of-poscar

### PR DESCRIPTION
**Pull request by Leimeroth**
Sets target forces directly in structure XML instead of using modified POSCARs. This allows to use structures with arbitrary order of species.
Requires https://gitlab.com/atomicrex/atomicrex/-/merge_requests/51 to work.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Is this part of `atomicrex=1.0.4` ?

**Comment by Leimeroth** [comment]
> Is this part of `atomicrex=1.0.4` ? 

Yes

**Comment by jan-janssen** [comment]
Atomicrex 1.0.4 was just released on conda-forge, so I think it might make sense to track these dependencies in the repository as well.

**Comment by Leimeroth** [comment]
I think the codacy error is something general and not related to the changes in this PR.
```
2024-04-19 09:31:04.990Z  warn [ReportRules] Failed to upload coverage report /home/runner/work/pyiron_potentialfit/pyiron_potentialfit/coverage.xml: Error doing a post to https://api.codacy.com/2.0/gh/pyiron/pyiron_potentialfit/commit/c1f369ad3ab5077b9593eee78baa90611a9a5d7f/coverage/python: exhausted retries due to API Error: could not find repository.  - (ReportRules.scala:59)
```
Do you have an idea what causes it @jan-janssen ?

**Comment by jan-janssen** [comment]
Yes, I got the same error in https://github.com/pyiron/pyiron_potentialfit/pull/65

**Comment by pmrv** [comment]
Yes, codacy is not setup for this repository and I haven't figured out how to disable it for now.  Can be ignored.

**Comment by Leimeroth** [comment]
I am not allowed to merge.

**Review by pmrv — APPROVED** [review]

**Comment by pmrv** [comment]
> I am not allowed to merge.

Sorry, I'm experimenting with the branch rules.  In theory [this](https://github.com/pyiron/pyiron_potentialfit/blob/3821184a360c0c9e7549c0e12707f8de3fda1627/.github/CODEOWNERS#L3) should make you be able to merge this in atomicrex, but it doesn't seem to work.

**Comment by pmrv** [comment]
> > I am not allowed to merge.
> 
> Sorry, I'm experimenting with the branch rules. In theory [this](https://github.com/pyiron/pyiron_potentialfit/blob/3821184a360c0c9e7549c0e12707f8de3fda1627/.github/CODEOWNERS#L3) should make you be able to merge this in atomicrex, but it doesn't seem to work.

I think now it does.  Try again later, otherwise I'll just merge it tonight.

**Pull request merged**
